unit svc_Dict_TLB;

// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// PASTLWTR : $Revision:   1.88.1.0.1.0  $
// File generated on 24.06.2004 16:12:00 from Type Library described below.

// ************************************************************************ //
// Type Lib: C:\projects\Ural\Wst\Filter\AppServer\UNFilterApp.tlb (1)
// IID\LCID: {586E5A62-8BD7-4516-880F-E7681D0B8997}\0
// Helpfile: 
// DepndLst: 
//   (1) v1.0 Midas, (C:\WINNT\System32\midas.dll)
//   (2) v2.0 stdole, (C:\WINNT\system32\stdole2.tlb)
//   (3) v4.0 StdVCL, (C:\WINNT\System32\STDVCL40.DLL)
// ************************************************************************ //
{$TYPEDADDRESS OFF} // Unit must be compiled without type-checked pointers. 
interface

uses Windows, ActiveX, Classes, Graphics, OleServer, OleCtrls, StdVCL, 
  MIDAS;

// *********************************************************************//
// GUIDS declared in the TypeLibrary. Following prefixes are used:        
//   Type Libraries     : LIBID_xxxx                                      
//   CoClasses          : CLASS_xxxx                                      
//   DISPInterfaces     : DIID_xxxx                                       
//   Non-DISP interfaces: IID_xxxx                                        
// *********************************************************************//
const
  // TypeLibrary Major and minor versions
  svc_DictMajorVersion = 1;
  svc_DictMinorVersion = 0;

  LIBID_svc_Dict: TGUID = '{586E5A62-8BD7-4516-880F-E7681D0B8997}';

  IID_IDic: TGUID = '{ACDBA141-5AFC-4EA0-84E2-71947ABC7F66}';
  CLASS_Dic: TGUID = '{5F4D097E-5296-4553-813D-385D363107E8}';
type

// *********************************************************************//
// Forward declaration of types defined in TypeLibrary                    
// *********************************************************************//
  IDic = interface;
  IDicDisp = dispinterface;

// *********************************************************************//
// Declaration of CoClasses defined in Type Library                       
// (NOTE: Here we map each CoClass to its Default Interface)              
// *********************************************************************//
  Dic = IDic;


// *********************************************************************//
// Declaration of structures, unions and aliases.                         
// *********************************************************************//
  POleVariant1 = ^OleVariant; {*}
  PWordBool1 = ^WordBool; {*}


// *********************************************************************//
// Interface: IDic
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {ACDBA141-5AFC-4EA0-84E2-71947ABC7F66}
// *********************************************************************//
  IDic = interface(IAppServer)
    ['{ACDBA141-5AFC-4EA0-84E2-71947ABC7F66}']
    function  DoLogin(UserName: OleVariant; Password: OleVariant): Integer; safecall;
    function  CAGroup_Add(id_Bsn: Integer; AName: OleVariant; ShowInRoot: WordBool): Integer; safecall;
    function  CAGroup_Edit(ID: Integer; AName: OleVariant; ShowInRoot: WordBool): Integer; safecall;
    function  CAGroup_Del(ID: Integer): Integer; safecall;
    function  Get_id_User: OleVariant; safecall;
    function  Get_FIO: OleVariant; safecall;
    function  CurByID(ID: OleVariant; out AName: OleVariant; out AShortName: OleVariant; 
                      var RateRBL: OleVariant): Integer; safecall;
    function  ContrAgentAdd(AName: OleVariant; id_business: OleVariant; id_CAGroup: OleVariant; 
                            isOwn: WordBool; Id_Currency: OleVariant; Addr: OleVariant; 
                            Descr: OleVariant; ShowInRoot: WordBool): Integer; safecall;
    function  ContrAgentEdit(id_ContrAgent: Integer; AName: OleVariant; id_business: OleVariant; 
                             id_CAGroup: OleVariant; isOwn: WordBool; Disabled: WordBool; 
                             Id_Currency: OleVariant; Addr: OleVariant; Descr: OleVariant; 
                             ShowInRoot: WordBool): Integer; safecall;
    procedure BeginTruns; safecall;
    procedure CommitTrans; safecall;
    procedure RollbackTrans; safecall;
    function  ReprAdd(id_ContrAgent: OleVariant; isJur: WordBool; AName: OleVariant; 
                      FirstName: OleVariant; MiddleName: OleVariant; LastName: OleVariant; 
                      Id_Currency: OleVariant; Disabled: WordBool; Addr: OleVariant; 
                      Descr: OleVariant; id_Bsn_ex: OleVariant; NeedSend: Integer): Integer; safecall;
    function  ReprEdit(id_Repr: Integer; id_ContrAgent: OleVariant; isJur: WordBool; 
                       AName: OleVariant; FirstName: OleVariant; MiddleName: OleVariant; 
                       LastName: OleVariant; Id_Currency: OleVariant; Disabled: WordBool; 
                       Addr: OleVariant; Descr: OleVariant; NeedSend: Integer): Integer; safecall;
    function  ContrAgentSetGrp(id_ContrAgent: Integer; id_CAGroup: OleVariant): Integer; safecall;
    function  Ctg_GoodsEdit(id_Ctg: Integer; id_business: Integer; id_BaseCtg: OleVariant; 
                            AName: OleVariant; ShortName: OleVariant; DefPrice: OleVariant; 
                            Id_Currency: OleVariant; Disabled: WordBool): Integer; safecall;
    function  CtgByID(AType: Integer; ID: OleVariant; out AName: OleVariant): Integer; safecall;
    function  Ctg_RawAdd(id_business: Integer; id_BaseCtg: OleVariant; AName: OleVariant; 
                         ShortName: OleVariant; DefPrice: OleVariant; Id_Currency: OleVariant; 
                         Disabled: WordBool): Integer; safecall;
    function  Ctg_RawEdit(id_Ctg: Integer; id_business: Integer; id_BaseCtg: OleVariant; 
                          AName: OleVariant; ShortName: OleVariant; DefPrice: OleVariant; 
                          Id_Currency: OleVariant; Disabled: WordBool): Integer; safecall;
    function  Ctg_GoodsAdd(id_business: Integer; id_BaseCtg: OleVariant; AName: OleVariant; 
                           ShortName: OleVariant; DefPrice: OleVariant; Id_Currency: OleVariant; 
                           Disabled: WordBool): Integer; safecall;
    function  Ctg_ExtRawAdd(id_business: Integer; id_BaseCtg: OleVariant; AName: OleVariant; 
                            ShortName: OleVariant; DefPrice: OleVariant; Id_Currency: OleVariant; 
                            Disabled: WordBool): Integer; safecall;
    function  Ctg_ExtRawEdit(id_Ctg: Integer; id_business: Integer; id_BaseCtg: OleVariant; 
                             AName: OleVariant; ShortName: OleVariant; DefPrice: OleVariant; 
                             Id_Currency: OleVariant; Disabled: WordBool): Integer; safecall;
    function  Ctg_ServiceAdd(id_business: Integer; id_BaseCtg: OleVariant; AName: OleVariant; 
                             ShortName: OleVariant; DefPrice: OleVariant; Id_Currency: OleVariant; 
                             Disabled: WordBool): Integer; safecall;
    function  Ctg_ServiceEdit(id_Ctg: Integer; id_business: Integer; id_BaseCtg: OleVariant; 
                              AName: OleVariant; ShortName: OleVariant; DefPrice: OleVariant; 
                              Id_Currency: OleVariant; Disabled: WordBool): Integer; safecall;
    function  WareAdd(AType: Integer; id_Ctg: OleVariant; AName: OleVariant; ShortName: OleVariant; 
                      BarCode: OleVariant; Price: OleVariant; Id_Currency: OleVariant; 
                      Disabled: WordBool; id_Measure: OleVariant): Integer; safecall;
    function  WareEdit(AType: Integer; AID: Integer; id_Ctg: OleVariant; AName: OleVariant; 
                       ShortName: OleVariant; BarCode: OleVariant; Price: OleVariant; 
                       Id_Currency: OleVariant; Disabled: WordBool; id_Measure: OleVariant): Integer; safecall;
    function  BsnByID(ID: OleVariant; out AName: OleVariant): Integer; safecall;
    function  LC_OP_OperEdit(id_LC_Oper: Integer; OperVid: Integer; id_Replicator: OleVariant; 
                             id_UserCreator: Integer; id_Manager: OleVariant; 
                             id_business: OleVariant; Correct: WordBool; OperTypeIn: WordBool; 
                             Id_CurrencyOper: OleVariant; AmountOper: Double; 
                             id_Measure: OleVariant; PriceOper: OleVariant; RateOper: Double; 
                             Id_CurrencySys: OleVariant; SummSys: OleVariant; RateSys: OleVariant; 
                             id_Acc: OleVariant; id_Warehouse: OleVariant; id_Repr: OleVariant; 
                             id_CAWhouse: OleVariant; id_Warehouse_Ext: OleVariant; 
                             id_Acc_Ext: OleVariant; id_Equipment: OleVariant; 
                             id_Goods: OleVariant; id_Raw: OleVariant; id_ExtRaw: OleVariant; 
                             id_Service: OleVariant; id_Manufact: OleVariant; 
                             id_Manufact_Ext: OleVariant; Id_CurrencyInv: OleVariant; 
                             PriceInv: OleVariant; id_DocType: OleVariant; 
                             Imp_PayBasic: OleVariant; AccInv_PayAssignment: OleVariant; 
                             Contract: OleVariant): Integer; safecall;
    function  LC_OP_OperAdd(OperVid: Integer; id_Replicator: OleVariant; id_UserCreator: Integer; 
                            id_Manager: OleVariant; id_business: OleVariant; Correct: WordBool; 
                            OperTypeIn: WordBool; Id_CurrencyOper: OleVariant; AmountOper: Double; 
                            id_Measure: OleVariant; PriceOper: OleVariant; RateOper: Double; 
                            Id_CurrencySys: OleVariant; SummSys: OleVariant; RateSys: OleVariant; 
                            id_Acc: OleVariant; id_Warehouse: OleVariant; id_Repr: OleVariant; 
                            id_CAWhouse: OleVariant; id_Warehouse_Ext: OleVariant; 
                            id_Acc_Ext: OleVariant; id_Equipment: OleVariant; id_Goods: OleVariant; 
                            id_Raw: OleVariant; id_ExtRaw: OleVariant; id_Service: OleVariant; 
                            id_Manufact: OleVariant; id_Manufact_Ext: OleVariant; 
                            Id_CurrencyInv: OleVariant; PriceInv: OleVariant; 
                            id_LC_Oper_Ext: OleVariant; id_DocType: OleVariant; 
                            Imp_PayBasic: OleVariant; AccInv_PayAssignment: OleVariant; 
                            Contract: OleVariant): Integer; safecall;
    function  LC_OP_EmptyAdd(id_UserCreator: Integer; OperTypeIn: WordBool; id_DocType: OleVariant; 
                             Contract: OleVariant; OpComment: OleVariant; id_business: Integer; 
                             Imp_PayBasic: OleVariant; AccInv_PayAssignment: OleVariant): Integer; safecall;
    function  LC_OP_EmptyEdit(id_LC_Oper: Integer; id_UserCreator: Integer; id_DocType: OleVariant; 
                              Contract: OleVariant; OpComment: OleVariant; id_business: Integer; 
                              Imp_PayBasic: OleVariant; AccInv_PayAssignment: OleVariant): Integer; safecall;
    function  CA_CAWhouseAdd(id_Repr: Integer; AName: OleVariant; Addr: OleVariant; 
                             Descr: OleVariant): Integer; safecall;
    function  CA_CAWhouseEdit(id_CAWhouse: Integer; id_Repr: Integer; AName: OleVariant; 
                              Addr: OleVariant; Descr: OleVariant): Integer; safecall;
    function  CA_CAWhouseDel(id_CAWhouse: Integer): Integer; safecall;
    function  LC_OP_DEL(id_LC_Oper: Integer): Integer; safecall;
    function  OP_OperEdit(id_Oper: Integer; id_Manager: OleVariant; id_business: OleVariant; 
                          Correct: WordBool; OperTypeIn: WordBool; Id_CurrencyOper: OleVariant; 
                          AmountOper: Double; id_Measure: OleVariant; PriceOper: OleVariant; 
                          RateOper: Double; Id_CurrencySys: OleVariant; SummSys: OleVariant; 
                          RateSys: OleVariant; id_Acc: OleVariant; id_Warehouse: OleVariant; 
                          id_Repr: OleVariant; id_CAWhouse: OleVariant; 
                          id_Warehouse_Ext: OleVariant; id_Acc_Ext: OleVariant; 
                          id_Equipment: OleVariant; id_Goods: OleVariant; id_Raw: OleVariant; 
                          id_ExtRaw: OleVariant; id_Service: OleVariant; id_Manufact: OleVariant; 
                          id_Manufact_Ext: OleVariant; id_FormalDistrib: OleVariant; 
                          id_FuncDistrib: OleVariant; Koeff: OleVariant; 
                          Id_CurrencyInv: OleVariant; PriceInv: OleVariant; 
                          id_OperParent: OleVariant; OperState: Integer; id_UserCreator: Integer; 
                          id_DocType: OleVariant; Imp_PayBasic: OleVariant; 
                          AccInv_PayAssignment: OleVariant; Contract: OleVariant): Integer; safecall;
    function  SetUserForOper(id_User: OleVariant; id_Oper: Integer): Integer; safecall;
    function  OP_OperDel(id_Oper: Integer): Integer; safecall;
    function  OP_OperSetCheckDate(id_Oper: Integer; id_UserChecker: OleVariant): Integer; safecall;
    function  LC_Acc_Add(AName: OleVariant; id_Bsn: OleVariant; id_Group: OleVariant): Integer; safecall;
    function  LC_Acc_Edit(AID: Integer; AName: OleVariant; id_Group: OleVariant): Integer; safecall;
    function  LC_WH_Add(AName: OleVariant; id_Bsn: OleVariant; id_Group: OleVariant): Integer; safecall;
    function  LC_WH_Edit(AID: Integer; AName: OleVariant; id_Group: OleVariant): Integer; safecall;
    function  LC_EQ_Add(AName: OleVariant; id_Bsn: OleVariant; id_Group: OleVariant): Integer; safecall;
    function  LC_EQ_Edit(AID: Integer; AName: OleVariant; id_Group: OleVariant): Integer; safecall;
    function  LC_MN_Add(AName: OleVariant; id_Bsn: OleVariant; id_Group: OleVariant): Integer; safecall;
    function  LC_MN_Edit(AID: Integer; AName: OleVariant; id_Group: OleVariant): Integer; safecall;
    function  CH_Checked(AID: Integer; ObjID: Integer): Integer; safecall;
    function  OP_OperDelCheckDate(id_Oper: Integer): Integer; safecall;
    function  UNSel_AccBsn(Param1: OleVariant; var id_Bsn: OleVariant; var id_Group: OleVariant): Integer; safecall;
    function  UNSel_WHBsn(Param1: OleVariant; var id_Bsn: OleVariant; var id_Group: OleVariant): Integer; safecall;
    function  UNSel_ManufBsn(Param1: OleVariant; var id_Bsn: OleVariant; var id_Group: OleVariant): Integer; safecall;
    function  UNSel_CABsn(Param1: Integer; out isOwn: WordBool; out id_CAGroup: OleVariant): Integer; safecall;
    function  UNSel_ReprBsn_v2(Param1: Integer; var isOwn: WordBool; var id_CAGroup: OleVariant; 
                               var id_Ca: OleVariant; var id_Repr_Group: OleVariant; 
                               var id_Bsn: OleVariant): Integer; safecall;
    function  UNSel_EQBsn(Param1: Integer): Integer; safecall;
    function  UNSel_PL_RawInf(Param1: Integer): Integer; safecall;
    function  PL_Ctg_ExtRawDel(Param1: Integer): Integer; safecall;
    function  PL_Ctg_GoodsDel(Param1: Integer): Integer; safecall;
    function  PL_Ctg_RawDel(Param1: Integer): Integer; safecall;
    function  PL_Ctg_ServiceDel(Param1: Integer): Integer; safecall;
    function  PL_ExtRawDel(Param1: Integer): Integer; safecall;
    function  PL_GoodsDel(Param1: Integer): Integer; safecall;
    function  PL_RawDel(Param1: Integer): Integer; safecall;
    function  PL_ServiceDel(Param1: Integer): Integer; safecall;
    function  CA_ContrAgentDel(Param1: Integer): Integer; safecall;
    function  CA_ReprDel(Param1: Integer): Integer; safecall;
    function  UNSel_PL_GoodsInf(Param1: Integer): Integer; safecall;
    function  UNSel_PL_ExtRawInf(Param1: Integer): Integer; safecall;
    function  UNSel_PL_ServiceInf(Param1: Integer): Integer; safecall;
    function  OP_OperSetOperState(id_Oper: Integer; OperState: Integer): Integer; safecall;
    function  BsnNumByID(AID: Integer; var Param2: OleVariant): Integer; safecall;
    function  CheckGoods(Param1: OleVariant): Integer; safecall;
    function  CheckRaw(Param1: OleVariant): Integer; safecall;
    function  CheckExtRaw(Param1: OleVariant): Integer; safecall;
    function  CheckService(Param1: OleVariant): Integer; safecall;
    function  PL_GetDefsGoods(AID_Ctg: Integer; out Price: OleVariant; out ID_Cur: OleVariant): Integer; safecall;
    function  PL_GetDefsRaw(AID_Ctg: Integer; out Price: OleVariant; out ID_Cur: OleVariant): Integer; safecall;
    function  PL_GetDefsExtRaw(AID_Ctg: Integer; out Price: OleVariant; out ID_Cur: OleVariant): Integer; safecall;
    function  PL_GetDefsService(AID_Ctg: Integer; out Price: OleVariant; out ID_Cur: OleVariant): Integer; safecall;
    function  PL_GetDefPriceGoods(AID_Ctg: Integer; id_Warehouse: OleVariant; 
                                  out Price: OleVariant; out ID_Cur: OleVariant; 
                                  out TotalAmount: Double): Integer; safecall;
    function  PL_GetDefPriceRaw(AID_Ctg: Integer; id_Warehouse: OleVariant; out Price: OleVariant; 
                                out ID_Cur: OleVariant; out TotalAmount: Double): Integer; safecall;
    function  PL_GetDefPriceExtRaw(AID_Ctg: Integer; id_Warehouse: OleVariant; 
                                   out Price: OleVariant; out ID_Cur: OleVariant; 
                                   out TotalAmount: Double): Integer; safecall;
    function  PL_GetDefPriceService(AID_Ctg: Integer; out Price: OleVariant; 
                                    out ID_Cur: OleVariant; out TotalAmount: Double): Integer; safecall;
    function  OP_OperAdd(OperVid: Integer; id_Manager: OleVariant; id_business: OleVariant; 
                         Correct: WordBool; OperTypeIn: WordBool; Id_CurrencyOper: OleVariant; 
                         AmountOper: Double; id_Measure: OleVariant; PriceOper: OleVariant; 
                         RateOper: Double; Id_CurrencySys: OleVariant; SummSys: OleVariant; 
                         RateSys: OleVariant; id_Acc: OleVariant; id_Warehouse: OleVariant; 
                         id_Repr: OleVariant; id_CAWhouse: OleVariant; 
                         id_Warehouse_Ext: OleVariant; id_Acc_Ext: OleVariant; 
                         id_Equipment: OleVariant; id_Goods: OleVariant; id_Raw: OleVariant; 
                         id_ExtRaw: OleVariant; id_Service: OleVariant; id_Manufact: OleVariant; 
                         id_Manufact_Ext: OleVariant; id_FormalDistrib: OleVariant; 
                         id_FuncDistrib: OleVariant; Koeff: OleVariant; Id_CurrencyInv: OleVariant; 
                         PriceInv: OleVariant; id_OperParent: OleVariant; OperState: Integer; 
                         id_UserCreator: Integer; id_DocType: OleVariant; Imp_PayBasic: OleVariant; 
                         AccInv_PayAssignment: OleVariant; Contract: OleVariant): Integer; safecall;
    function  OP_OperGetEditID(id_OperParent: Integer): Integer; safecall;
    function  OP_DoCancel(id_Oper: Integer): Integer; safecall;
    function  OP_DoOk(id_Oper: Integer): Integer; safecall;
    function  LNK_Equipment(id_Old: Integer; id_New: Integer): WordBool; safecall;
    function  LNK_Acc(id_Old: Integer; id_New: Integer): WordBool; safecall;
    function  LNK_Warehouse(id_Old: Integer; id_New: Integer): WordBool; safecall;
    function  LNK_Repr(id_Old: Integer; id_New: Integer): WordBool; safecall;
    function  LNK_Manufact(id_Old: Integer; id_New: Integer): WordBool; safecall;
    function  LNK_ExtRaw(id_Old: Integer; id_New: Integer): WordBool; safecall;
    function  LNK_Goods(id_Old: Integer; id_New: Integer): WordBool; safecall;
    function  LNK_Raw(id_Old: Integer; id_New: Integer): WordBool; safecall;
    function  LNK_Service(id_Old: Integer; id_New: Integer): WordBool; safecall;
    function  OP_BuffAdd(AName: OleVariant): Integer; safecall;
    function  OP_BuffDel(id_Buff: Integer): Integer; safecall;
    function  OP_BuffEdit(id_Buff: Integer; AName: OleVariant): Integer; safecall;
    function  PL_UN_WareCtgGetProp(id_Ctg: Integer; ID_TYPE: Integer): OleVariant; safecall;
    function  CA_CAGroupGetProp(id_CAGroup: OleVariant): OleVariant; safecall;
    function  CA_CAGetProp(id_ContrAgent: OleVariant): OleVariant; safecall;
    function  DD_DayOpen(id_business: Integer; VirtDate: TDateTime): Integer; safecall;
    function  DD_DayClose(id_business: Integer): Integer; safecall;
    function  DD_DayGetProp(id_business: Integer): OleVariant; safecall;
    function  PL_GetAccSum(id_Acc: Integer; out TotalSum: Double): Integer; safecall;
    function  OP_FuncDistribAdd(AName: OleVariant; id_Bsn: Integer): Integer; safecall;
    function  OP_FuncDistribEdit(id_FuncDistrib: Integer; AName: OleVariant): Integer; safecall;
    function  OP_FuncDistribDel(id_FuncDistrib: Integer): Integer; safecall;
    function  OP_FormalDistribAdd(AName: OleVariant; id_Bsn: Integer): Integer; safecall;
    function  OP_FormalDistribEdit(id_FormalDistrib: Integer; AName: OleVariant): Integer; safecall;
    function  OP_FormalDistribDel(id_FormalDistrib: Integer): Integer; safecall;
    function  GetWH(ID: Integer; var AName: OleVariant; var ABsnName: OleVariant): Integer; safecall;
    function  GetOperNum(id_Oper: Integer): OleVariant; safecall;
    function  Rights_GetUserRights(id_Func: Integer; id_business: OleVariant; id_User: Integer): Integer; safecall;
    function  Rights_GetFuncName(id_Func: Integer): OleVariant; safecall;
    function  OP_Oper_ExtDataNamesEdit(id_Oper_ExtDataNames: Integer; id_business: Integer; 
                                       AType: Integer; NumPrm: Integer; ParName: OleVariant; 
                                       AVisible: WordBool): Integer; safecall;
    function  UN_Check_Ctg_Ware(WareType: Integer; id_business: Integer; id_Ctg: OleVariant; 
                                AName: OleVariant; id_real: OleVariant): Integer; safecall;
    function  UN_Check_Ware(WareType: Integer; id_Ctg: OleVariant; AName: OleVariant; 
                            id_real: OleVariant): Integer; safecall;
    function  UN_Check_CAGroup(id_business: Integer; AName: OleVariant; id_real: OleVariant): Integer; safecall;
    function  UN_Check_CA_ContrAgent(id_business: Integer; AName: OleVariant; id_real: OleVariant): Integer; safecall;
    function  UN_Check_CA_Repr(id_ContrAgent: Integer; AName: OleVariant; id_real: OleVariant): Integer; safecall;
    function  UN_Sel_PL_ExtRawCtg(AID: Integer): Integer; safecall;
    function  UN_Sel_PL_GoodsCtg(AID: Integer): Integer; safecall;
    function  UN_Sel_PL_RawCtg(AID: Integer): Integer; safecall;
    function  UN_Sel_PL_ServiceCtg(AID: Integer): Integer; safecall;
    function  LC_OP_OperSetCheckDate(id_LC_Oper: Integer): Integer; safecall;
    function  LC_OP_OperDelCheckDate(id_LC_Oper: Integer): Integer; safecall;
    procedure LC_SetBaseName(AName: OleVariant); safecall;
    function  CH_Deleted(AID: Integer; AObjID: Integer): Integer; safecall;
    function  RP_WHStateDates_Get: OleVariant; safecall;
    function  xxx_Group_Check_v2(ObjID: Integer; id_business: Integer; AName: OleVariant; 
                                 id_real: OleVariant): Integer; safecall;
    function  xxx_Group_Add_v2(ObjID: Integer; id_business: Integer; AName: OleVariant; 
                               ShowInRoot: WordBool): Integer; safecall;
    function  xxx_Group_Edit_v2(ObjID: Integer; id_Group: Integer; AName: OleVariant; 
                                ShowInRoot: WordBool): Integer; safecall;
    function  xxx_Group_Del_v2(ObjID: Integer; id_Group: Integer): Integer; safecall;
    function  xxx_SetGrp(ObjID: Integer; AID: Integer; id_Group: OleVariant): Integer; safecall;
    function  Acc_Del(id_Acc: Integer): Integer; safecall;
    function  Acc_Edit(id_Acc: OleVariant; AccName: OleVariant; Bank: OleVariant; 
                       id_business: OleVariant; PrsnAccName: OleVariant; CorrAccName: OleVariant; 
                       Inn: OleVariant; BIK: OleVariant; Disabled: OleVariant; NeedSend: WordBool; 
                       id_Group: OleVariant; ShowInRoot: WordBool): Integer; safecall;
    function  MN_Del(id_MN: Integer): Integer; safecall;
    function  MN_Edit(id_Manufact: OleVariant; ManufactName: OleVariant; id_business: OleVariant; 
                      Addr: OleVariant; Disabled: OleVariant; NeedSend: WordBool; 
                      id_Group: OleVariant; ShowInRoot: WordBool): Integer; safecall;
    function  WH_Del(id_WH: Integer): Integer; safecall;
    function  WH_Edit(id_Warehouse: OleVariant; AName: OleVariant; id_business: OleVariant; 
                      Addr: OleVariant; Disabled: OleVariant; NeedSend: WordBool; 
                      id_Group: OleVariant; ShowInRoot: WordBool): Integer; safecall;
    function  UNSel_ReprBsn(Param1: Integer; var isOwn: WordBool; var id_CAGroup: OleVariant; 
                            var id_Ca: OleVariant): Integer; safecall;
    function  ReprAdd_LC(isJur: WordBool; AName: OleVariant; FirstName: OleVariant; 
                         MiddleName: OleVariant; LastName: OleVariant; Id_Currency: OleVariant; 
                         Disabled: WordBool; Addr: OleVariant; Descr: OleVariant; 
                         id_Bsn_ex: OleVariant; id_Group: OleVariant): Integer; safecall;
    function  ReprEdit_LC(id_Repr: Integer; isJur: WordBool; AName: OleVariant; 
                          FirstName: OleVariant; MiddleName: OleVariant; LastName: OleVariant; 
                          Id_Currency: OleVariant; Disabled: WordBool; Addr: OleVariant; 
                          Descr: OleVariant; id_Group: OleVariant): Integer; safecall;
    function  GetAccName(id_Acc: Integer): OleVariant; safecall;
    function  GetAccGroupName(id_Acc_Group: Integer): OleVariant; safecall;
    function  GetWHName(id_WH: Integer): OleVariant; safecall;
    function  GetWHGroupName(id_WHGroup: Integer): OleVariant; safecall;
    function  GetCAName(id_Ca: Integer): OleVariant; safecall;
    function  GetCAGroupName(id_CAGroup: Integer): OleVariant; safecall;
    function  DD_MaxDay(id_business: Integer): OleVariant; safecall;
    function  OP_OperAdd_v2(OperVid: Integer; id_Manager: OleVariant; id_business: OleVariant; 
                            Correct: WordBool; OperTypeIn: WordBool; Id_CurrencyOper: OleVariant; 
                            PriceFinOper: OleVariant; RateOper: Double; Id_CurrencySys: OleVariant; 
                            SummSysFin: OleVariant; RateSys: OleVariant; id_Repr: OleVariant; 
                            id_Acc: OleVariant; id_Acc_Ext: OleVariant; id_Warehouse: OleVariant; 
                            id_Warehouse_Ext: OleVariant; id_Manufact: OleVariant; 
                            id_Manufact_Ext: OleVariant; id_FormalDistrib: OleVariant; 
                            id_FuncDistrib: OleVariant; Koeff: OleVariant; 
                            Id_CurrencyInv: OleVariant; id_OperParent: OleVariant; 
                            OperState: Integer; id_UserCreator: OleVariant; id_DocType: OleVariant; 
                            Imp_PayBasic: OleVariant; AccInv_PayAssignment: OleVariant; 
                            Contract: OleVariant; OpComment: OleVariant; Dig1: OleVariant; 
                            Dig2: OleVariant; Dig3: OleVariant; Dig4: OleVariant; Dig5: OleVariant; 
                            Dig6: OleVariant; Dig7: OleVariant; Dig8: OleVariant; Dig9: OleVariant; 
                            Dig10: OleVariant; Dig11: OleVariant; Dig12: OleVariant; 
                            Dig13: OleVariant; Dig14: OleVariant; Dig15: OleVariant; 
                            Str1: OleVariant; Str2: OleVariant; Str3: OleVariant; Str4: OleVariant; 
                            Str5: OleVariant; Str6: OleVariant; Str7: OleVariant; Str8: OleVariant; 
                            Str9: OleVariant; Str10: OleVariant; Str11: OleVariant; 
                            Str12: OleVariant; Str13: OleVariant; Str14: OleVariant; 
                            Str15: OleVariant; Date1: OleVariant; Date2: OleVariant; 
                            Date3: OleVariant; Date4: OleVariant; Date5: OleVariant; 
                            Date6: OleVariant; Date7: OleVariant; Date8: OleVariant; 
                            Date9: OleVariant; Date10: OleVariant; Date11: OleVariant; 
                            Date12: OleVariant; Date13: OleVariant; Date14: OleVariant; 
                            Date15: OleVariant; out RetVal: Integer): Integer; stdcall;
    function  OP_OperEdit_v2(id_Oper: Integer; OperVid: Integer; id_Manager: OleVariant; 
                             id_business: OleVariant; Correct: WordBool; OperTypeIn: WordBool; 
                             Id_CurrencyOper: OleVariant; PriceFinOper: OleVariant; 
                             RateOper: Double; Id_CurrencySys: OleVariant; SummSysFin: OleVariant; 
                             RateSys: OleVariant; id_Repr: OleVariant; id_Acc: OleVariant; 
                             id_Acc_Ext: OleVariant; id_Warehouse: OleVariant; 
                             id_Warehouse_Ext: OleVariant; id_Manufact: OleVariant; 
                             id_Manufact_Ext: OleVariant; id_FormalDistrib: OleVariant; 
                             id_FuncDistrib: OleVariant; Koeff: OleVariant; 
                             Id_CurrencyInv: OleVariant; id_OperParent: OleVariant; 
                             OperState: Integer; id_UserCreator: OleVariant; 
                             id_DocType: OleVariant; Imp_PayBasic: OleVariant; 
                             AccInv_PayAssignment: OleVariant; Contract: OleVariant; 
                             OpComment: OleVariant; Dig1: OleVariant; Dig2: OleVariant; 
                             Dig3: OleVariant; Dig4: OleVariant; Dig5: OleVariant; 
                             Dig6: OleVariant; Dig7: OleVariant; Dig8: OleVariant; 
                             Dig9: OleVariant; Dig10: OleVariant; Dig11: OleVariant; 
                             Dig12: OleVariant; Dig13: OleVariant; Dig14: OleVariant; 
                             Dig15: OleVariant; Str1: OleVariant; Str2: OleVariant; 
                             Str3: OleVariant; Str4: OleVariant; Str5: OleVariant; 
                             Str6: OleVariant; Str7: OleVariant; Str8: OleVariant; 
                             Str9: OleVariant; Str10: OleVariant; Str11: OleVariant; 
                             Str12: OleVariant; Str13: OleVariant; Str14: OleVariant; 
                             Str15: OleVariant; Date1: OleVariant; Date2: OleVariant; 
                             Date3: OleVariant; Date4: OleVariant; Date5: OleVariant; 
                             Date6: OleVariant; Date7: OleVariant; Date8: OleVariant; 
                             Date9: OleVariant; Date10: OleVariant; Date11: OleVariant; 
                             Date12: OleVariant; Date13: OleVariant; Date14: OleVariant; 
                             Date15: OleVariant; out RetVal: Integer): Integer; stdcall;
    function  OP_OperSetOperState_v2(id_Oper: Integer; OperState: Integer): Integer; safecall;
    function  OP_OperDelCheckDate_v2(id_Oper: Integer): Integer; safecall;
    function  OP_OperSetCheckDate_v2(id_Oper: Integer; id_UserChecker: OleVariant): Integer; safecall;
    function  PL_WareMeasureGet(id_Goods: OleVariant; id_Raw: OleVariant; id_ExtRaw: OleVariant; 
                                var id_Measure: OleVariant; var ShortName: OleVariant): OleVariant; safecall;
    function  GetBsnCur(id_Bsn: Integer): Integer; safecall;
    function  UN_ShowInRoot(id_Acc: OleVariant; id_Acc_Group: OleVariant; id_Warehouse: OleVariant; 
                            id_Warehouse_Group: OleVariant; id_ContrAgent: OleVariant; 
                            id_CAGroup: OleVariant; id_Manufact: OleVariant; 
                            id_Manufact_Group: OleVariant; ShowInRoot: WordBool): Integer; safecall;
    function  GetWateCtg(id_Goods: OleVariant; id_Raw: OleVariant; id_ExtRaw: OleVariant; 
                         is_Service: OleVariant): OleVariant; safecall;
    function  DCh_Oper(id_business: Integer; OperVid: Integer; id_UserCreator: OleVariant; 
                       DateLocal: OleVariant; Correct: WordBool; OperTypeIn: WordBool; 
                       CurrencyOperName: OleVariant; PriceFinOper: OleVariant; 
                       CurrencySysName: OleVariant; SummSysFin: OleVariant; AccName: OleVariant; 
                       AccName_Ext: OleVariant; WarehouseName: OleVariant; 
                       WarehouseName_Ext: OleVariant; ManufactName: OleVariant; 
                       ManufactName_Ext: OleVariant; ReprName: OleVariant; CAName: OleVariant; 
                       Koeff: Integer; FormalDistribName: OleVariant; FuncDistribName: OleVariant; 
                       Imp_PayBasic: OleVariant; AccInv_PayAssignment: OleVariant; 
                       OpComment: OleVariant; Contract: OleVariant; ReprName_Ex: OleVariant; 
                       id_Replicator: OleVariant; id_LC_Oper: OleVariant): Integer; safecall;
    function  DCh_OperWare(id_Oper: Integer; CtgName: OleVariant; GoodsName: OleVariant; 
                           RawName: OleVariant; ExtRawName: OleVariant; ServiceName: OleVariant; 
                           MeasureName: OleVariant; AmountOper: Double; PriceOper: OleVariant; 
                           SummSys: OleVariant): Integer; safecall;
    function  OP_BuffAddItem(id_Buff: Integer; id_Oper: Integer): Integer; safecall;
    function  OP_OperWareAdd_BackToCA(id_Oper: Integer; id_Goods: OleVariant; id_Raw: OleVariant; 
                                      id_ExtRaw: OleVariant; id_Service: OleVariant; 
                                      id_Measure: OleVariant; Amount: OleVariant; 
                                      PriceOper: OleVariant; SummSys: OleVariant; OupByInv: Integer): Integer; safecall;
    function  PL_WareNameGet(id_Goods: OleVariant; id_Raw: OleVariant; id_ExtRaw: OleVariant; 
                             id_Service: OleVariant; var AName: OleVariant; 
                             var ShortName: OleVariant): Integer; safecall;
    function  LC_OP_OperAdd_v2(OperVid: Integer; id_business: OleVariant; Correct: WordBool; 
                               OperTypeIn: WordBool; Id_CurrencyOper: OleVariant; 
                               PriceFinOper: OleVariant; Id_CurrencySys: OleVariant; 
                               SummSysFin: OleVariant; id_Acc: OleVariant; id_Acc_Ext: OleVariant; 
                               id_Warehouse: OleVariant; id_Warehouse_Ext: OleVariant; 
                               id_Manufact: OleVariant; id_Manufact_Ext: OleVariant; 
                               id_Repr: OleVariant; id_UserCreator: OleVariant; 
                               id_LC_Oper_Ext: OleVariant; id_DocType: OleVariant; 
                               Imp_PayBasic: OleVariant; AccInv_PayAssignment: OleVariant; 
                               Contract: OleVariant; OpComment: OleVariant): Integer; safecall;
    function  LC_OP_OperEdit_v2(id_LC_Oper: Integer; OperVid: Integer; id_business: OleVariant; 
                                Correct: WordBool; OperTypeIn: WordBool; 
                                Id_CurrencyOper: OleVariant; PriceFinOper: OleVariant; 
                                Id_CurrencySys: OleVariant; SummSysFin: OleVariant; 
                                id_Acc: OleVariant; id_Acc_Ext: OleVariant; 
                                id_Warehouse: OleVariant; id_Warehouse_Ext: OleVariant; 
                                id_Manufact: OleVariant; id_Manufact_Ext: OleVariant; 
                                id_Repr: OleVariant; id_UserCreator: OleVariant; 
                                id_LC_Oper_Ext: OleVariant; id_DocType: OleVariant; 
                                Imp_PayBasic: OleVariant; AccInv_PayAssignment: OleVariant; 
                                Contract: OleVariant; OpComment: OleVariant): Integer; safecall;
    function  DCh_Oper_LC(id_business: Integer; OperVid: Integer; id_UserCreator: OleVariant; 
                          Correct: WordBool; OperTypeIn: WordBool; CurrencyOperName: OleVariant; 
                          PriceFinOper: OleVariant; CurrencySysName: OleVariant; 
                          SummSysFin: OleVariant; AccName: OleVariant; AccName_Ext: OleVariant; 
                          WarehouseName: OleVariant; WarehouseName_Ext: OleVariant; 
                          ManufactName: OleVariant; ManufactName_Ext: OleVariant; 
                          ReprName: OleVariant; Imp_PayBasic: OleVariant; 
                          AccInv_PayAssignment: OleVariant; OpComment: OleVariant; 
                          Contract: OleVariant): Integer; safecall;
    function  DCh_OperWare_LC(id_LC_Oper: Integer; CtgName: OleVariant; GoodsName: OleVariant; 
                              RawName: OleVariant; ExtRawName: OleVariant; ServiceName: OleVariant; 
                              MeasureName: OleVariant; AmountOper: Double; PriceOper: OleVariant; 
                              SummSys: OleVariant): Integer; safecall;
    function  ExpSetID(id_Oper: Integer; id_LC_Oper: Integer): Integer; safecall;
    function  OP_EmptyAdd(id_UserCreator: Integer; OperTypeIn: WordBool; id_DocType: OleVariant; 
                          Contract: OleVariant; OpComment: OleVariant; id_business: Integer; 
                          Imp_PayBasic: OleVariant; AccInv_PayAssignment: OleVariant): Integer; safecall;
    function  OP_EmptyEdit(id_Oper: Integer; id_UserCreator: Integer; id_DocType: OleVariant; 
                           Contract: OleVariant; OpComment: OleVariant; id_business: Integer; 
                           Imp_PayBasic: OleVariant; AccInv_PayAssignment: OleVariant): Integer; safecall;
    function  SetUserDetail_2(Act: OleVariant; ID: OleVariant; FirstName: OleVariant; 
                              MiddleName: OleVariant; LastName: OleVariant; Login: OleVariant; 
                              Password: OleVariant; PspSeries: OleVariant; PspNumber: OleVariant; 
                              PspPlace: OleVariant; Pspdate: OleVariant; PspAddr: OleVariant; 
                              AddrReal: OleVariant; Phones: OleVariant; Emails: OleVariant; 
                              OrgPost: OleVariant; Disabled: OleVariant; isRelp: WordBool): Integer; safecall;
    procedure SetUserGroups(ID: OleVariant; Ids: OleVariant); safecall;
    function  SetGroupDetail(Act: OleVariant; ID: OleVariant; GroupName: OleVariant; 
                             Disabled: OleVariant): Integer; safecall;
    function  SetMeasureDetail(Act: OleVariant; ID: OleVariant; MeasureName: OleVariant; 
                               ShortName: OleVariant; id_BaseMeasure: OleVariant; 
                               id_business: OleVariant; Koef: OleVariant; Disabled: OleVariant): Integer; safecall;
    procedure SetMeasureBusiness(ID: OleVariant; Ids: OleVariant); safecall;
    function  SetGroupDetail1(Act: OleVariant; ID: OleVariant; GroupName: OleVariant; 
                              Disabled: OleVariant): Integer; safecall;
    function  SetBusinessDetail(Act: OleVariant; ID: OleVariant; BusinessName: OleVariant; 
                                ShortName: OleVariant; Id_Currency: OleVariant; Num: OleVariant; 
                                Disabled: OleVariant): Integer; safecall;
    function  SetReplicatorDetail(Act: OleVariant; ID: OleVariant; ReplicatorName: OleVariant; 
                                  ShortName: OleVariant; Login: OleVariant; Password: OleVariant; 
                                  DelPeriod: OleVariant; Disabled: OleVariant): Integer; safecall;
    procedure SetReplBusiness(ID: OleVariant; Ids: OleVariant); safecall;
    function  SnglObj_Acc(id_User: Integer; out ObjName: OleVariant; out ObjID: OleVariant; 
                          out BsnName: OleVariant; out id_business: OleVariant): Integer; safecall;
    function  SnglObj_MN(id_User: Integer; out ObjName: OleVariant; out ObjID: OleVariant; 
                         out BsnName: OleVariant; out id_business: OleVariant): Integer; safecall;
    function  SnglObj_wh(id_User: Integer; out ObjName: OleVariant; out ObjID: OleVariant; 
                         out BsnName: OleVariant; out id_business: OleVariant): Integer; safecall;
    function  SnglObj_CA(id_User: Integer; out ObjName: OleVariant; out ObjID: OleVariant; 
                         out BsnName: OleVariant; out id_business: OleVariant): Integer; safecall;
    function  MSG_Add(Body: OleVariant; id_User: Integer; WasRead: WordBool; DateClose: OleVariant; 
                      RepBody: OleVariant; id_State: OleVariant): Integer; safecall;
    function  MSG_Edit(id_Msg: Integer; Body: OleVariant; id_User: Integer; WasRead: WordBool; 
                       DateClose: OleVariant; RepBody: OleVariant; id_State: OleVariant): Integer; safecall;
    function  MSG_SetClosed(id_Msg: Integer; DateClose: OleVariant): Integer; safecall;
    function  MSG_SetWasRead(id_Msg: Integer; WasRead: WordBool): Integer; safecall;
    property id_User: OleVariant read Get_id_User;
    property FIO: OleVariant read Get_FIO;
  end;

// *********************************************************************//
// DispIntf:  IDicDisp
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {ACDBA141-5AFC-4EA0-84E2-71947ABC7F66}
// *********************************************************************//
  IDicDisp = dispinterface
    ['{ACDBA141-5AFC-4EA0-84E2-71947ABC7F66}']
    function  DoLogin(UserName: OleVariant; Password: OleVariant): Integer; dispid 2;
    function  CAGroup_Add(id_Bsn: Integer; AName: OleVariant; ShowInRoot: WordBool): Integer; dispid 1;
    function  CAGroup_Edit(ID: Integer; AName: OleVariant; ShowInRoot: WordBool): Integer; dispid 3;
    function  CAGroup_Del(ID: Integer): Integer; dispid 4;
    property id_User: OleVariant readonly dispid 5;
    property FIO: OleVariant readonly dispid 6;
    function  CurByID(ID: OleVariant; out AName: OleVariant; out AShortName: OleVariant; 
                      var RateRBL: OleVariant): Integer; dispid 7;
    function  ContrAgentAdd(AName: OleVariant; id_business: OleVariant; id_CAGroup: OleVariant; 
                            isOwn: WordBool; Id_Currency: OleVariant; Addr: OleVariant; 
                            Descr: OleVariant; ShowInRoot: WordBool): Integer; dispid 8;
    function  ContrAgentEdit(id_ContrAgent: Integer; AName: OleVariant; id_business: OleVariant; 
                             id_CAGroup: OleVariant; isOwn: WordBool; Disabled: WordBool; 
                             Id_Currency: OleVariant; Addr: OleVariant; Descr: OleVariant; 
                             ShowInRoot: WordBool): Integer; dispid 9;
    procedure BeginTruns; dispid 10;
    procedure CommitTrans; dispid 11;
    procedure RollbackTrans; dispid 12;
    function  ReprAdd(id_ContrAgent: OleVariant; isJur: WordBool; AName: OleVariant; 
                      FirstName: OleVariant; MiddleName: OleVariant; LastName: OleVariant; 
                      Id_Currency: OleVariant; Disabled: WordBool; Addr: OleVariant; 
                      Descr: OleVariant; id_Bsn_ex: OleVariant; NeedSend: Integer): Integer; dispid 13;
    function  ReprEdit(id_Repr: Integer; id_ContrAgent: OleVariant; isJur: WordBool; 
                       AName: OleVariant; FirstName: OleVariant; MiddleName: OleVariant; 
                       LastName: OleVariant; Id_Currency: OleVariant; Disabled: WordBool; 
                       Addr: OleVariant; Descr: OleVariant; NeedSend: Integer): Integer; dispid 14;
    function  ContrAgentSetGrp(id_ContrAgent: Integer; id_CAGroup: OleVariant): Integer; dispid 15;
    function  Ctg_GoodsEdit(id_Ctg: Integer; id_business: Integer; id_BaseCtg: OleVariant; 
                            AName: OleVariant; ShortName: OleVariant; DefPrice: OleVariant; 
                            Id_Currency: OleVariant; Disabled: WordBool): Integer; dispid 17;
    function  CtgByID(AType: Integer; ID: OleVariant; out AName: OleVariant): Integer; dispid 18;
    function  Ctg_RawAdd(id_business: Integer; id_BaseCtg: OleVariant; AName: OleVariant; 
                         ShortName: OleVariant; DefPrice: OleVariant; Id_Currency: OleVariant; 
                         Disabled: WordBool): Integer; dispid 19;
    function  Ctg_RawEdit(id_Ctg: Integer; id_business: Integer; id_BaseCtg: OleVariant; 
                          AName: OleVariant; ShortName: OleVariant; DefPrice: OleVariant; 
                          Id_Currency: OleVariant; Disabled: WordBool): Integer; dispid 25;
    function  Ctg_GoodsAdd(id_business: Integer; id_BaseCtg: OleVariant; AName: OleVariant; 
                           ShortName: OleVariant; DefPrice: OleVariant; Id_Currency: OleVariant; 
                           Disabled: WordBool): Integer; dispid 16;
    function  Ctg_ExtRawAdd(id_business: Integer; id_BaseCtg: OleVariant; AName: OleVariant; 
                            ShortName: OleVariant; DefPrice: OleVariant; Id_Currency: OleVariant; 
                            Disabled: WordBool): Integer; dispid 30;
    function  Ctg_ExtRawEdit(id_Ctg: Integer; id_business: Integer; id_BaseCtg: OleVariant; 
                             AName: OleVariant; ShortName: OleVariant; DefPrice: OleVariant; 
                             Id_Currency: OleVariant; Disabled: WordBool): Integer; dispid 32;
    function  Ctg_ServiceAdd(id_business: Integer; id_BaseCtg: OleVariant; AName: OleVariant; 
                             ShortName: OleVariant; DefPrice: OleVariant; Id_Currency: OleVariant; 
                             Disabled: WordBool): Integer; dispid 34;
    function  Ctg_ServiceEdit(id_Ctg: Integer; id_business: Integer; id_BaseCtg: OleVariant; 
                              AName: OleVariant; ShortName: OleVariant; DefPrice: OleVariant; 
                              Id_Currency: OleVariant; Disabled: WordBool): Integer; dispid 37;
    function  WareAdd(AType: Integer; id_Ctg: OleVariant; AName: OleVariant; ShortName: OleVariant; 
                      BarCode: OleVariant; Price: OleVariant; Id_Currency: OleVariant; 
                      Disabled: WordBool; id_Measure: OleVariant): Integer; dispid 20;
    function  WareEdit(AType: Integer; AID: Integer; id_Ctg: OleVariant; AName: OleVariant; 
                       ShortName: OleVariant; BarCode: OleVariant; Price: OleVariant; 
                       Id_Currency: OleVariant; Disabled: WordBool; id_Measure: OleVariant): Integer; dispid 22;
    function  BsnByID(ID: OleVariant; out AName: OleVariant): Integer; dispid 23;
    function  LC_OP_OperEdit(id_LC_Oper: Integer; OperVid: Integer; id_Replicator: OleVariant; 
                             id_UserCreator: Integer; id_Manager: OleVariant; 
                             id_business: OleVariant; Correct: WordBool; OperTypeIn: WordBool; 
                             Id_CurrencyOper: OleVariant; AmountOper: Double; 
                             id_Measure: OleVariant; PriceOper: OleVariant; RateOper: Double; 
                             Id_CurrencySys: OleVariant; SummSys: OleVariant; RateSys: OleVariant; 
                             id_Acc: OleVariant; id_Warehouse: OleVariant; id_Repr: OleVariant; 
                             id_CAWhouse: OleVariant; id_Warehouse_Ext: OleVariant; 
                             id_Acc_Ext: OleVariant; id_Equipment: OleVariant; 
                             id_Goods: OleVariant; id_Raw: OleVariant; id_ExtRaw: OleVariant; 
                             id_Service: OleVariant; id_Manufact: OleVariant; 
                             id_Manufact_Ext: OleVariant; Id_CurrencyInv: OleVariant; 
                             PriceInv: OleVariant; id_DocType: OleVariant; 
                             Imp_PayBasic: OleVariant; AccInv_PayAssignment: OleVariant; 
                             Contract: OleVariant): Integer; dispid 27;
    function  LC_OP_OperAdd(OperVid: Integer; id_Replicator: OleVariant; id_UserCreator: Integer; 
                            id_Manager: OleVariant; id_business: OleVariant; Correct: WordBool; 
                            OperTypeIn: WordBool; Id_CurrencyOper: OleVariant; AmountOper: Double; 
                            id_Measure: OleVariant; PriceOper: OleVariant; RateOper: Double; 
                            Id_CurrencySys: OleVariant; SummSys: OleVariant; RateSys: OleVariant; 
                            id_Acc: OleVariant; id_Warehouse: OleVariant; id_Repr: OleVariant; 
                            id_CAWhouse: OleVariant; id_Warehouse_Ext: OleVariant; 
                            id_Acc_Ext: OleVariant; id_Equipment: OleVariant; id_Goods: OleVariant; 
                            id_Raw: OleVariant; id_ExtRaw: OleVariant; id_Service: OleVariant; 
                            id_Manufact: OleVariant; id_Manufact_Ext: OleVariant; 
                            Id_CurrencyInv: OleVariant; PriceInv: OleVariant; 
                            id_LC_Oper_Ext: OleVariant; id_DocType: OleVariant; 
                            Imp_PayBasic: OleVariant; AccInv_PayAssignment: OleVariant; 
                            Contract: OleVariant): Integer; dispid 29;
    function  LC_OP_EmptyAdd(id_UserCreator: Integer; OperTypeIn: WordBool; id_DocType: OleVariant; 
                             Contract: OleVariant; OpComment: OleVariant; id_business: Integer; 
                             Imp_PayBasic: OleVariant; AccInv_PayAssignment: OleVariant): Integer; dispid 28;
    function  LC_OP_EmptyEdit(id_LC_Oper: Integer; id_UserCreator: Integer; id_DocType: OleVariant; 
                              Contract: OleVariant; OpComment: OleVariant; id_business: Integer; 
                              Imp_PayBasic: OleVariant; AccInv_PayAssignment: OleVariant): Integer; dispid 33;
    function  CA_CAWhouseAdd(id_Repr: Integer; AName: OleVariant; Addr: OleVariant; 
                             Descr: OleVariant): Integer; dispid 31;
    function  CA_CAWhouseEdit(id_CAWhouse: Integer; id_Repr: Integer; AName: OleVariant; 
                              Addr: OleVariant; Descr: OleVariant): Integer; dispid 36;
    function  CA_CAWhouseDel(id_CAWhouse: Integer): Integer; dispid 38;
    function  LC_OP_DEL(id_LC_Oper: Integer): Integer; dispid 39;
    function  OP_OperEdit(id_Oper: Integer; id_Manager: OleVariant; id_business: OleVariant; 
                          Correct: WordBool; OperTypeIn: WordBool; Id_CurrencyOper: OleVariant; 
                          AmountOper: Double; id_Measure: OleVariant; PriceOper: OleVariant; 
                          RateOper: Double; Id_CurrencySys: OleVariant; SummSys: OleVariant; 
                          RateSys: OleVariant; id_Acc: OleVariant; id_Warehouse: OleVariant; 
                          id_Repr: OleVariant; id_CAWhouse: OleVariant; 
                          id_Warehouse_Ext: OleVariant; id_Acc_Ext: OleVariant; 
                          id_Equipment: OleVariant; id_Goods: OleVariant; id_Raw: OleVariant; 
                          id_ExtRaw: OleVariant; id_Service: OleVariant; id_Manufact: OleVariant; 
                          id_Manufact_Ext: OleVariant; id_FormalDistrib: OleVariant; 
                          id_FuncDistrib: OleVariant; Koeff: OleVariant; 
                          Id_CurrencyInv: OleVariant; PriceInv: OleVariant; 
                          id_OperParent: OleVariant; OperState: Integer; id_UserCreator: Integer; 
                          id_DocType: OleVariant; Imp_PayBasic: OleVariant; 
                          AccInv_PayAssignment: OleVariant; Contract: OleVariant): Integer; dispid 41;
    function  SetUserForOper(id_User: OleVariant; id_Oper: Integer): Integer; dispid 21;
    function  OP_OperDel(id_Oper: Integer): Integer; dispid 24;
    function  OP_OperSetCheckDate(id_Oper: Integer; id_UserChecker: OleVariant): Integer; dispid 26;
    function  LC_Acc_Add(AName: OleVariant; id_Bsn: OleVariant; id_Group: OleVariant): Integer; dispid 35;
    function  LC_Acc_Edit(AID: Integer; AName: OleVariant; id_Group: OleVariant): Integer; dispid 40;
    function  LC_WH_Add(AName: OleVariant; id_Bsn: OleVariant; id_Group: OleVariant): Integer; dispid 44;
    function  LC_WH_Edit(AID: Integer; AName: OleVariant; id_Group: OleVariant): Integer; dispid 45;
    function  LC_EQ_Add(AName: OleVariant; id_Bsn: OleVariant; id_Group: OleVariant): Integer; dispid 47;
    function  LC_EQ_Edit(AID: Integer; AName: OleVariant; id_Group: OleVariant): Integer; dispid 49;
    function  LC_MN_Add(AName: OleVariant; id_Bsn: OleVariant; id_Group: OleVariant): Integer; dispid 50;
    function  LC_MN_Edit(AID: Integer; AName: OleVariant; id_Group: OleVariant): Integer; dispid 51;
    function  CH_Checked(AID: Integer; ObjID: Integer): Integer; dispid 42;
    function  OP_OperDelCheckDate(id_Oper: Integer): Integer; dispid 43;
    function  UNSel_AccBsn(Param1: OleVariant; var id_Bsn: OleVariant; var id_Group: OleVariant): Integer; dispid 46;
    function  UNSel_WHBsn(Param1: OleVariant; var id_Bsn: OleVariant; var id_Group: OleVariant): Integer; dispid 48;
    function  UNSel_ManufBsn(Param1: OleVariant; var id_Bsn: OleVariant; var id_Group: OleVariant): Integer; dispid 52;
    function  UNSel_CABsn(Param1: Integer; out isOwn: WordBool; out id_CAGroup: OleVariant): Integer; dispid 53;
    function  UNSel_ReprBsn_v2(Param1: Integer; var isOwn: WordBool; var id_CAGroup: OleVariant; 
                               var id_Ca: OleVariant; var id_Repr_Group: OleVariant; 
                               var id_Bsn: OleVariant): Integer; dispid 54;
    function  UNSel_EQBsn(Param1: Integer): Integer; dispid 55;
    function  UNSel_PL_RawInf(Param1: Integer): Integer; dispid 56;
    function  PL_Ctg_ExtRawDel(Param1: Integer): Integer; dispid 57;
    function  PL_Ctg_GoodsDel(Param1: Integer): Integer; dispid 58;
    function  PL_Ctg_RawDel(Param1: Integer): Integer; dispid 59;
    function  PL_Ctg_ServiceDel(Param1: Integer): Integer; dispid 60;
    function  PL_ExtRawDel(Param1: Integer): Integer; dispid 61;
    function  PL_GoodsDel(Param1: Integer): Integer; dispid 62;
    function  PL_RawDel(Param1: Integer): Integer; dispid 63;
    function  PL_ServiceDel(Param1: Integer): Integer; dispid 64;
    function  CA_ContrAgentDel(Param1: Integer): Integer; dispid 65;
    function  CA_ReprDel(Param1: Integer): Integer; dispid 66;
    function  UNSel_PL_GoodsInf(Param1: Integer): Integer; dispid 67;
    function  UNSel_PL_ExtRawInf(Param1: Integer): Integer; dispid 68;
    function  UNSel_PL_ServiceInf(Param1: Integer): Integer; dispid 69;
    function  OP_OperSetOperState(id_Oper: Integer; OperState: Integer): Integer; dispid 70;
    function  BsnNumByID(AID: Integer; var Param2: OleVariant): Integer; dispid 71;
    function  CheckGoods(Param1: OleVariant): Integer; dispid 72;
    function  CheckRaw(Param1: OleVariant): Integer; dispid 73;
    function  CheckExtRaw(Param1: OleVariant): Integer; dispid 74;
    function  CheckService(Param1: OleVariant): Integer; dispid 75;
    function  PL_GetDefsGoods(AID_Ctg: Integer; out Price: OleVariant; out ID_Cur: OleVariant): Integer; dispid 77;
    function  PL_GetDefsRaw(AID_Ctg: Integer; out Price: OleVariant; out ID_Cur: OleVariant): Integer; dispid 80;
    function  PL_GetDefsExtRaw(AID_Ctg: Integer; out Price: OleVariant; out ID_Cur: OleVariant): Integer; dispid 81;
    function  PL_GetDefsService(AID_Ctg: Integer; out Price: OleVariant; out ID_Cur: OleVariant): Integer; dispid 82;
    function  PL_GetDefPriceGoods(AID_Ctg: Integer; id_Warehouse: OleVariant; 
                                  out Price: OleVariant; out ID_Cur: OleVariant; 
                                  out TotalAmount: Double): Integer; dispid 83;
    function  PL_GetDefPriceRaw(AID_Ctg: Integer; id_Warehouse: OleVariant; out Price: OleVariant; 
                                out ID_Cur: OleVariant; out TotalAmount: Double): Integer; dispid 85;
    function  PL_GetDefPriceExtRaw(AID_Ctg: Integer; id_Warehouse: OleVariant; 
                                   out Price: OleVariant; out ID_Cur: OleVariant; 
                                   out TotalAmount: Double): Integer; dispid 87;
    function  PL_GetDefPriceService(AID_Ctg: Integer; out Price: OleVariant; 
                                    out ID_Cur: OleVariant; out TotalAmount: Double): Integer; dispid 89;
    function  OP_OperAdd(OperVid: Integer; id_Manager: OleVariant; id_business: OleVariant; 
                         Correct: WordBool; OperTypeIn: WordBool; Id_CurrencyOper: OleVariant; 
                         AmountOper: Double; id_Measure: OleVariant; PriceOper: OleVariant; 
                         RateOper: Double; Id_CurrencySys: OleVariant; SummSys: OleVariant; 
                         RateSys: OleVariant; id_Acc: OleVariant; id_Warehouse: OleVariant; 
                         id_Repr: OleVariant; id_CAWhouse: OleVariant; 
                         id_Warehouse_Ext: OleVariant; id_Acc_Ext: OleVariant; 
                         id_Equipment: OleVariant; id_Goods: OleVariant; id_Raw: OleVariant; 
                         id_ExtRaw: OleVariant; id_Service: OleVariant; id_Manufact: OleVariant; 
                         id_Manufact_Ext: OleVariant; id_FormalDistrib: OleVariant; 
                         id_FuncDistrib: OleVariant; Koeff: OleVariant; Id_CurrencyInv: OleVariant; 
                         PriceInv: OleVariant; id_OperParent: OleVariant; OperState: Integer; 
                         id_UserCreator: Integer; id_DocType: OleVariant; Imp_PayBasic: OleVariant; 
                         AccInv_PayAssignment: OleVariant; Contract: OleVariant): Integer; dispid 90;
    function  OP_OperGetEditID(id_OperParent: Integer): Integer; dispid 76;
    function  OP_DoCancel(id_Oper: Integer): Integer; dispid 78;
    function  OP_DoOk(id_Oper: Integer): Integer; dispid 79;
    function  LNK_Equipment(id_Old: Integer; id_New: Integer): WordBool; dispid 84;
    function  LNK_Acc(id_Old: Integer; id_New: Integer): WordBool; dispid 88;
    function  LNK_Warehouse(id_Old: Integer; id_New: Integer): WordBool; dispid 92;
    function  LNK_Repr(id_Old: Integer; id_New: Integer): WordBool; dispid 94;
    function  LNK_Manufact(id_Old: Integer; id_New: Integer): WordBool; dispid 95;
    function  LNK_ExtRaw(id_Old: Integer; id_New: Integer): WordBool; dispid 98;
    function  LNK_Goods(id_Old: Integer; id_New: Integer): WordBool; dispid 100;
    function  LNK_Raw(id_Old: Integer; id_New: Integer): WordBool; dispid 102;
    function  LNK_Service(id_Old: Integer; id_New: Integer): WordBool; dispid 104;
    function  OP_BuffAdd(AName: OleVariant): Integer; dispid 86;
    function  OP_BuffDel(id_Buff: Integer): Integer; dispid 91;
    function  OP_BuffEdit(id_Buff: Integer; AName: OleVariant): Integer; dispid 93;
    function  PL_UN_WareCtgGetProp(id_Ctg: Integer; ID_TYPE: Integer): OleVariant; dispid 96;
    function  CA_CAGroupGetProp(id_CAGroup: OleVariant): OleVariant; dispid 97;
    function  CA_CAGetProp(id_ContrAgent: OleVariant): OleVariant; dispid 120;
    function  DD_DayOpen(id_business: Integer; VirtDate: TDateTime): Integer; dispid 99;
    function  DD_DayClose(id_business: Integer): Integer; dispid 103;
    function  DD_DayGetProp(id_business: Integer): OleVariant; dispid 105;
    function  PL_GetAccSum(id_Acc: Integer; out TotalSum: Double): Integer; dispid 101;
    function  OP_FuncDistribAdd(AName: OleVariant; id_Bsn: Integer): Integer; dispid 106;
    function  OP_FuncDistribEdit(id_FuncDistrib: Integer; AName: OleVariant): Integer; dispid 107;
    function  OP_FuncDistribDel(id_FuncDistrib: Integer): Integer; dispid 108;
    function  OP_FormalDistribAdd(AName: OleVariant; id_Bsn: Integer): Integer; dispid 110;
    function  OP_FormalDistribEdit(id_FormalDistrib: Integer; AName: OleVariant): Integer; dispid 112;
    function  OP_FormalDistribDel(id_FormalDistrib: Integer): Integer; dispid 115;
    function  GetWH(ID: Integer; var AName: OleVariant; var ABsnName: OleVariant): Integer; dispid 109;
    function  GetOperNum(id_Oper: Integer): OleVariant; dispid 111;
    function  Rights_GetUserRights(id_Func: Integer; id_business: OleVariant; id_User: Integer): Integer; dispid 113;
    function  Rights_GetFuncName(id_Func: Integer): OleVariant; dispid 114;
    function  OP_Oper_ExtDataNamesEdit(id_Oper_ExtDataNames: Integer; id_business: Integer; 
                                       AType: Integer; NumPrm: Integer; ParName: OleVariant; 
                                       AVisible: WordBool): Integer; dispid 116;
    function  UN_Check_Ctg_Ware(WareType: Integer; id_business: Integer; id_Ctg: OleVariant; 
                                AName: OleVariant; id_real: OleVariant): Integer; dispid 117;
    function  UN_Check_Ware(WareType: Integer; id_Ctg: OleVariant; AName: OleVariant; 
                            id_real: OleVariant): Integer; dispid 118;
    function  UN_Check_CAGroup(id_business: Integer; AName: OleVariant; id_real: OleVariant): Integer; dispid 119;
    function  UN_Check_CA_ContrAgent(id_business: Integer; AName: OleVariant; id_real: OleVariant): Integer; dispid 121;
    function  UN_Check_CA_Repr(id_ContrAgent: Integer; AName: OleVariant; id_real: OleVariant): Integer; dispid 122;
    function  UN_Sel_PL_ExtRawCtg(AID: Integer): Integer; dispid 123;
    function  UN_Sel_PL_GoodsCtg(AID: Integer): Integer; dispid 124;
    function  UN_Sel_PL_RawCtg(AID: Integer): Integer; dispid 125;
    function  UN_Sel_PL_ServiceCtg(AID: Integer): Integer; dispid 126;
    function  LC_OP_OperSetCheckDate(id_LC_Oper: Integer): Integer; dispid 127;
    function  LC_OP_OperDelCheckDate(id_LC_Oper: Integer): Integer; dispid 128;
    procedure LC_SetBaseName(AName: OleVariant); dispid 129;
    function  CH_Deleted(AID: Integer; AObjID: Integer): Integer; dispid 130;
    function  RP_WHStateDates_Get: OleVariant; dispid 131;
    function  xxx_Group_Check_v2(ObjID: Integer; id_business: Integer; AName: OleVariant; 
                                 id_real: OleVariant): Integer; dispid 132;
    function  xxx_Group_Add_v2(ObjID: Integer; id_business: Integer; AName: OleVariant; 
                               ShowInRoot: WordBool): Integer; dispid 133;
    function  xxx_Group_Edit_v2(ObjID: Integer; id_Group: Integer; AName: OleVariant; 
                                ShowInRoot: WordBool): Integer; dispid 135;
    function  xxx_Group_Del_v2(ObjID: Integer; id_Group: Integer): Integer; dispid 134;
    function  xxx_SetGrp(ObjID: Integer; AID: Integer; id_Group: OleVariant): Integer; dispid 136;
    function  Acc_Del(id_Acc: Integer): Integer; dispid 137;
    function  Acc_Edit(id_Acc: OleVariant; AccName: OleVariant; Bank: OleVariant; 
                       id_business: OleVariant; PrsnAccName: OleVariant; CorrAccName: OleVariant; 
                       Inn: OleVariant; BIK: OleVariant; Disabled: OleVariant; NeedSend: WordBool; 
                       id_Group: OleVariant; ShowInRoot: WordBool): Integer; dispid 139;
    function  MN_Del(id_MN: Integer): Integer; dispid 138;
    function  MN_Edit(id_Manufact: OleVariant; ManufactName: OleVariant; id_business: OleVariant; 
                      Addr: OleVariant; Disabled: OleVariant; NeedSend: WordBool; 
                      id_Group: OleVariant; ShowInRoot: WordBool): Integer; dispid 142;
    function  WH_Del(id_WH: Integer): Integer; dispid 141;
    function  WH_Edit(id_Warehouse: OleVariant; AName: OleVariant; id_business: OleVariant; 
                      Addr: OleVariant; Disabled: OleVariant; NeedSend: WordBool; 
                      id_Group: OleVariant; ShowInRoot: WordBool): Integer; dispid 144;
    function  UNSel_ReprBsn(Param1: Integer; var isOwn: WordBool; var id_CAGroup: OleVariant; 
                            var id_Ca: OleVariant): Integer; dispid 147;
    function  ReprAdd_LC(isJur: WordBool; AName: OleVariant; FirstName: OleVariant; 
                         MiddleName: OleVariant; LastName: OleVariant; Id_Currency: OleVariant; 
                         Disabled: WordBool; Addr: OleVariant; Descr: OleVariant; 
                         id_Bsn_ex: OleVariant; id_Group: OleVariant): Integer; dispid 151;
    function  ReprEdit_LC(id_Repr: Integer; isJur: WordBool; AName: OleVariant; 
                          FirstName: OleVariant; MiddleName: OleVariant; LastName: OleVariant; 
                          Id_Currency: OleVariant; Disabled: WordBool; Addr: OleVariant; 
                          Descr: OleVariant; id_Group: OleVariant): Integer; dispid 153;
    function  GetAccName(id_Acc: Integer): OleVariant; dispid 140;
    function  GetAccGroupName(id_Acc_Group: Integer): OleVariant; dispid 143;
    function  GetWHName(id_WH: Integer): OleVariant; dispid 145;
    function  GetWHGroupName(id_WHGroup: Integer): OleVariant; dispid 146;
    function  GetCAName(id_Ca: Integer): OleVariant; dispid 148;
    function  GetCAGroupName(id_CAGroup: Integer): OleVariant; dispid 149;
    function  DD_MaxDay(id_business: Integer): OleVariant; dispid 150;
    function  OP_OperAdd_v2(OperVid: Integer; id_Manager: OleVariant; id_business: OleVariant; 
                            Correct: WordBool; OperTypeIn: WordBool; Id_CurrencyOper: OleVariant; 
                            PriceFinOper: OleVariant; RateOper: Double; Id_CurrencySys: OleVariant; 
                            SummSysFin: OleVariant; RateSys: OleVariant; id_Repr: OleVariant; 
                            id_Acc: OleVariant; id_Acc_Ext: OleVariant; id_Warehouse: OleVariant; 
                            id_Warehouse_Ext: OleVariant; id_Manufact: OleVariant; 
                            id_Manufact_Ext: OleVariant; id_FormalDistrib: OleVariant; 
                            id_FuncDistrib: OleVariant; Koeff: OleVariant; 
                            Id_CurrencyInv: OleVariant; id_OperParent: OleVariant; 
                            OperState: Integer; id_UserCreator: OleVariant; id_DocType: OleVariant; 
                            Imp_PayBasic: OleVariant; AccInv_PayAssignment: OleVariant; 
                            Contract: OleVariant; OpComment: OleVariant; Dig1: OleVariant; 
                            Dig2: OleVariant; Dig3: OleVariant; Dig4: OleVariant; Dig5: OleVariant; 
                            Dig6: OleVariant; Dig7: OleVariant; Dig8: OleVariant; Dig9: OleVariant; 
                            Dig10: OleVariant; Dig11: OleVariant; Dig12: OleVariant; 
                            Dig13: OleVariant; Dig14: OleVariant; Dig15: OleVariant; 
                            Str1: OleVariant; Str2: OleVariant; Str3: OleVariant; Str4: OleVariant; 
                            Str5: OleVariant; Str6: OleVariant; Str7: OleVariant; Str8: OleVariant; 
                            Str9: OleVariant; Str10: OleVariant; Str11: OleVariant; 
                            Str12: OleVariant; Str13: OleVariant; Str14: OleVariant; 
                            Str15: OleVariant; Date1: OleVariant; Date2: OleVariant; 
                            Date3: OleVariant; Date4: OleVariant; Date5: OleVariant; 
                            Date6: OleVariant; Date7: OleVariant; Date8: OleVariant; 
                            Date9: OleVariant; Date10: OleVariant; Date11: OleVariant; 
                            Date12: OleVariant; Date13: OleVariant; Date14: OleVariant; 
                            Date15: OleVariant; out RetVal: Integer): Integer; dispid 155;
    function  OP_OperEdit_v2(id_Oper: Integer; OperVid: Integer; id_Manager: OleVariant; 
                             id_business: OleVariant; Correct: WordBool; OperTypeIn: WordBool; 
                             Id_CurrencyOper: OleVariant; PriceFinOper: OleVariant; 
                             RateOper: Double; Id_CurrencySys: OleVariant; SummSysFin: OleVariant; 
                             RateSys: OleVariant; id_Repr: OleVariant; id_Acc: OleVariant; 
                             id_Acc_Ext: OleVariant; id_Warehouse: OleVariant; 
                             id_Warehouse_Ext: OleVariant; id_Manufact: OleVariant; 
                             id_Manufact_Ext: OleVariant; id_FormalDistrib: OleVariant; 
                             id_FuncDistrib: OleVariant; Koeff: OleVariant; 
                             Id_CurrencyInv: OleVariant; id_OperParent: OleVariant; 
                             OperState: Integer; id_UserCreator: OleVariant; 
                             id_DocType: OleVariant; Imp_PayBasic: OleVariant; 
                             AccInv_PayAssignment: OleVariant; Contract: OleVariant; 
                             OpComment: OleVariant; Dig1: OleVariant; Dig2: OleVariant; 
                             Dig3: OleVariant; Dig4: OleVariant; Dig5: OleVariant; 
                             Dig6: OleVariant; Dig7: OleVariant; Dig8: OleVariant; 
                             Dig9: OleVariant; Dig10: OleVariant; Dig11: OleVariant; 
                             Dig12: OleVariant; Dig13: OleVariant; Dig14: OleVariant; 
                             Dig15: OleVariant; Str1: OleVariant; Str2: OleVariant; 
                             Str3: OleVariant; Str4: OleVariant; Str5: OleVariant; 
                             Str6: OleVariant; Str7: OleVariant; Str8: OleVariant; 
                             Str9: OleVariant; Str10: OleVariant; Str11: OleVariant; 
                             Str12: OleVariant; Str13: OleVariant; Str14: OleVariant; 
                             Str15: OleVariant; Date1: OleVariant; Date2: OleVariant; 
                             Date3: OleVariant; Date4: OleVariant; Date5: OleVariant; 
                             Date6: OleVariant; Date7: OleVariant; Date8: OleVariant; 
                             Date9: OleVariant; Date10: OleVariant; Date11: OleVariant; 
                             Date12: OleVariant; Date13: OleVariant; Date14: OleVariant; 
                             Date15: OleVariant; out RetVal: Integer): Integer; dispid 156;
    function  OP_OperSetOperState_v2(id_Oper: Integer; OperState: Integer): Integer; dispid 160;
    function  OP_OperDelCheckDate_v2(id_Oper: Integer): Integer; dispid 163;
    function  OP_OperSetCheckDate_v2(id_Oper: Integer; id_UserChecker: OleVariant): Integer; dispid 1667;
    function  PL_WareMeasureGet(id_Goods: OleVariant; id_Raw: OleVariant; id_ExtRaw: OleVariant; 
                                var id_Measure: OleVariant; var ShortName: OleVariant): OleVariant; dispid 152;
    function  GetBsnCur(id_Bsn: Integer): Integer; dispid 154;
    function  UN_ShowInRoot(id_Acc: OleVariant; id_Acc_Group: OleVariant; id_Warehouse: OleVariant; 
                            id_Warehouse_Group: OleVariant; id_ContrAgent: OleVariant; 
                            id_CAGroup: OleVariant; id_Manufact: OleVariant; 
                            id_Manufact_Group: OleVariant; ShowInRoot: WordBool): Integer; dispid 157;
    function  GetWateCtg(id_Goods: OleVariant; id_Raw: OleVariant; id_ExtRaw: OleVariant; 
                         is_Service: OleVariant): OleVariant; dispid 158;
    function  DCh_Oper(id_business: Integer; OperVid: Integer; id_UserCreator: OleVariant; 
                       DateLocal: OleVariant; Correct: WordBool; OperTypeIn: WordBool; 
                       CurrencyOperName: OleVariant; PriceFinOper: OleVariant; 
                       CurrencySysName: OleVariant; SummSysFin: OleVariant; AccName: OleVariant; 
                       AccName_Ext: OleVariant; WarehouseName: OleVariant; 
                       WarehouseName_Ext: OleVariant; ManufactName: OleVariant; 
                       ManufactName_Ext: OleVariant; ReprName: OleVariant; CAName: OleVariant; 
                       Koeff: Integer; FormalDistribName: OleVariant; FuncDistribName: OleVariant; 
                       Imp_PayBasic: OleVariant; AccInv_PayAssignment: OleVariant; 
                       OpComment: OleVariant; Contract: OleVariant; ReprName_Ex: OleVariant; 
                       id_Replicator: OleVariant; id_LC_Oper: OleVariant): Integer; dispid 159;
    function  DCh_OperWare(id_Oper: Integer; CtgName: OleVariant; GoodsName: OleVariant; 
                           RawName: OleVariant; ExtRawName: OleVariant; ServiceName: OleVariant; 
                           MeasureName: OleVariant; AmountOper: Double; PriceOper: OleVariant; 
                           SummSys: OleVariant): Integer; dispid 161;
    function  OP_BuffAddItem(id_Buff: Integer; id_Oper: Integer): Integer; dispid 162;
    function  OP_OperWareAdd_BackToCA(id_Oper: Integer; id_Goods: OleVariant; id_Raw: OleVariant; 
                                      id_ExtRaw: OleVariant; id_Service: OleVariant; 
                                      id_Measure: OleVariant; Amount: OleVariant; 
                                      PriceOper: OleVariant; SummSys: OleVariant; OupByInv: Integer): Integer; dispid 164;
    function  PL_WareNameGet(id_Goods: OleVariant; id_Raw: OleVariant; id_ExtRaw: OleVariant; 
                             id_Service: OleVariant; var AName: OleVariant; 
                             var ShortName: OleVariant): Integer; dispid 171;
    function  LC_OP_OperAdd_v2(OperVid: Integer; id_business: OleVariant; Correct: WordBool; 
                               OperTypeIn: WordBool; Id_CurrencyOper: OleVariant; 
                               PriceFinOper: OleVariant; Id_CurrencySys: OleVariant; 
                               SummSysFin: OleVariant; id_Acc: OleVariant; id_Acc_Ext: OleVariant; 
                               id_Warehouse: OleVariant; id_Warehouse_Ext: OleVariant; 
                               id_Manufact: OleVariant; id_Manufact_Ext: OleVariant; 
                               id_Repr: OleVariant; id_UserCreator: OleVariant; 
                               id_LC_Oper_Ext: OleVariant; id_DocType: OleVariant; 
                               Imp_PayBasic: OleVariant; AccInv_PayAssignment: OleVariant; 
                               Contract: OleVariant; OpComment: OleVariant): Integer; dispid 169;
    function  LC_OP_OperEdit_v2(id_LC_Oper: Integer; OperVid: Integer; id_business: OleVariant; 
                                Correct: WordBool; OperTypeIn: WordBool; 
                                Id_CurrencyOper: OleVariant; PriceFinOper: OleVariant; 
                                Id_CurrencySys: OleVariant; SummSysFin: OleVariant; 
                                id_Acc: OleVariant; id_Acc_Ext: OleVariant; 
                                id_Warehouse: OleVariant; id_Warehouse_Ext: OleVariant; 
                                id_Manufact: OleVariant; id_Manufact_Ext: OleVariant; 
                                id_Repr: OleVariant; id_UserCreator: OleVariant; 
                                id_LC_Oper_Ext: OleVariant; id_DocType: OleVariant; 
                                Imp_PayBasic: OleVariant; AccInv_PayAssignment: OleVariant; 
                                Contract: OleVariant; OpComment: OleVariant): Integer; dispid 170;
    function  DCh_Oper_LC(id_business: Integer; OperVid: Integer; id_UserCreator: OleVariant; 
                          Correct: WordBool; OperTypeIn: WordBool; CurrencyOperName: OleVariant; 
                          PriceFinOper: OleVariant; CurrencySysName: OleVariant; 
                          SummSysFin: OleVariant; AccName: OleVariant; AccName_Ext: OleVariant; 
                          WarehouseName: OleVariant; WarehouseName_Ext: OleVariant; 
                          ManufactName: OleVariant; ManufactName_Ext: OleVariant; 
                          ReprName: OleVariant; Imp_PayBasic: OleVariant; 
                          AccInv_PayAssignment: OleVariant; OpComment: OleVariant; 
                          Contract: OleVariant): Integer; dispid 178;
    function  DCh_OperWare_LC(id_LC_Oper: Integer; CtgName: OleVariant; GoodsName: OleVariant; 
                              RawName: OleVariant; ExtRawName: OleVariant; ServiceName: OleVariant; 
                              MeasureName: OleVariant; AmountOper: Double; PriceOper: OleVariant; 
                              SummSys: OleVariant): Integer; dispid 177;
    function  ExpSetID(id_Oper: Integer; id_LC_Oper: Integer): Integer; dispid 165;
    function  OP_EmptyAdd(id_UserCreator: Integer; OperTypeIn: WordBool; id_DocType: OleVariant; 
                          Contract: OleVariant; OpComment: OleVariant; id_business: Integer; 
                          Imp_PayBasic: OleVariant; AccInv_PayAssignment: OleVariant): Integer; dispid 172;
    function  OP_EmptyEdit(id_Oper: Integer; id_UserCreator: Integer; id_DocType: OleVariant; 
                           Contract: OleVariant; OpComment: OleVariant; id_business: Integer; 
                           Imp_PayBasic: OleVariant; AccInv_PayAssignment: OleVariant): Integer; dispid 168;
    function  SetUserDetail_2(Act: OleVariant; ID: OleVariant; FirstName: OleVariant; 
                              MiddleName: OleVariant; LastName: OleVariant; Login: OleVariant; 
                              Password: OleVariant; PspSeries: OleVariant; PspNumber: OleVariant; 
                              PspPlace: OleVariant; Pspdate: OleVariant; PspAddr: OleVariant; 
                              AddrReal: OleVariant; Phones: OleVariant; Emails: OleVariant; 
                              OrgPost: OleVariant; Disabled: OleVariant; isRelp: WordBool): Integer; dispid 175;
    procedure SetUserGroups(ID: OleVariant; Ids: OleVariant); dispid 179;
    function  SetGroupDetail(Act: OleVariant; ID: OleVariant; GroupName: OleVariant; 
                             Disabled: OleVariant): Integer; dispid 182;
    function  SetMeasureDetail(Act: OleVariant; ID: OleVariant; MeasureName: OleVariant; 
                               ShortName: OleVariant; id_BaseMeasure: OleVariant; 
                               id_business: OleVariant; Koef: OleVariant; Disabled: OleVariant): Integer; dispid 185;
    procedure SetMeasureBusiness(ID: OleVariant; Ids: OleVariant); dispid 187;
    function  SetGroupDetail1(Act: OleVariant; ID: OleVariant; GroupName: OleVariant; 
                              Disabled: OleVariant): Integer; dispid 189;
    function  SetBusinessDetail(Act: OleVariant; ID: OleVariant; BusinessName: OleVariant; 
                                ShortName: OleVariant; Id_Currency: OleVariant; Num: OleVariant; 
                                Disabled: OleVariant): Integer; dispid 191;
    function  SetReplicatorDetail(Act: OleVariant; ID: OleVariant; ReplicatorName: OleVariant; 
                                  ShortName: OleVariant; Login: OleVariant; Password: OleVariant; 
                                  DelPeriod: OleVariant; Disabled: OleVariant): Integer; dispid 194;
    procedure SetReplBusiness(ID: OleVariant; Ids: OleVariant); dispid 197;
    function  SnglObj_Acc(id_User: Integer; out ObjName: OleVariant; out ObjID: OleVariant; 
                          out BsnName: OleVariant; out id_business: OleVariant): Integer; dispid 166;
    function  SnglObj_MN(id_User: Integer; out ObjName: OleVariant; out ObjID: OleVariant; 
                         out BsnName: OleVariant; out id_business: OleVariant): Integer; dispid 167;
    function  SnglObj_wh(id_User: Integer; out ObjName: OleVariant; out ObjID: OleVariant; 
                         out BsnName: OleVariant; out id_business: OleVariant): Integer; dispid 173;
    function  SnglObj_CA(id_User: Integer; out ObjName: OleVariant; out ObjID: OleVariant; 
                         out BsnName: OleVariant; out id_business: OleVariant): Integer; dispid 174;
    function  MSG_Add(Body: OleVariant; id_User: Integer; WasRead: WordBool; DateClose: OleVariant; 
                      RepBody: OleVariant; id_State: OleVariant): Integer; dispid 176;
    function  MSG_Edit(id_Msg: Integer; Body: OleVariant; id_User: Integer; WasRead: WordBool; 
                       DateClose: OleVariant; RepBody: OleVariant; id_State: OleVariant): Integer; dispid 183;
    function  MSG_SetClosed(id_Msg: Integer; DateClose: OleVariant): Integer; dispid 180;
    function  MSG_SetWasRead(id_Msg: Integer; WasRead: WordBool): Integer; dispid 181;
    function  AS_ApplyUpdates(const ProviderName: WideString; Delta: OleVariant; 
                              MaxErrors: Integer; out ErrorCount: Integer; var OwnerData: OleVariant): OleVariant; dispid 20000000;
    function  AS_GetRecords(const ProviderName: WideString; Count: Integer; out RecsOut: Integer; 
                            Options: Integer; const CommandText: WideString; 
                            var Params: OleVariant; var OwnerData: OleVariant): OleVariant; dispid 20000001;
    function  AS_DataRequest(const ProviderName: WideString; Data: OleVariant): OleVariant; dispid 20000002;
    function  AS_GetProviderNames: OleVariant; dispid 20000003;
    function  AS_GetParams(const ProviderName: WideString; var OwnerData: OleVariant): OleVariant; dispid 20000004;
    function  AS_RowRequest(const ProviderName: WideString; Row: OleVariant; RequestType: Integer; 
                            var OwnerData: OleVariant): OleVariant; dispid 20000005;
    procedure AS_Execute(const ProviderName: WideString; const CommandText: WideString; 
                         var Params: OleVariant; var OwnerData: OleVariant); dispid 20000006;
  end;

// *********************************************************************//
// The Class CoDic provides a Create and CreateRemote method to          
// create instances of the default interface IDic exposed by              
// the CoClass Dic. The functions are intended to be used by             
// clients wishing to automate the CoClass objects exposed by the         
// server of this typelibrary.                                            
// *********************************************************************//
  CoDic = class
    class function Create: IDic;
    class function CreateRemote(const MachineName: string): IDic;
  end;

implementation

uses ComObj;

class function CoDic.Create: IDic;
begin
  Result := CreateComObject(CLASS_Dic) as IDic;
end;

class function CoDic.CreateRemote(const MachineName: string): IDic;
begin
  Result := CreateRemoteComObject(MachineName, CLASS_Dic) as IDic;
end;

end.
